package com.example.demo.service;
import java.util.*;
import org.hibernate.service.spi.ServiceException;
import com.example.demo.domain.entity.App;

/**
 * Declares application specific functions
 * @author Sameera
 *
 */
public interface AppService {
	
	/**
	 * sets the currently logged in username
	 * @param uname The name of the currently logged in user
	 */
	 public void setUname(String uname);
	 
	 /**
	  * @return it returns currently logged in username
	  */
	 public String getUname();
	 
	 /**
	  * sets the id of a todo item which have to be edited
	  * @param upid The unique id of the todo item
	  */
	 public void setUpid(int upid);
	 
	 /**
	  * @return it returns the id of a todo item which have to be edited
	  */
	 public int getUpid();
	 
	 /**
	  * This method is to create new todo item
	  * @param n gets the value of the entered todo
	  * @exception ServiceException on service error
	  */
    public void newT(String n)throws ServiceException;
    
    /**
     * This method is to delete a todo item
     * @param id gets the autogenerated value which is unique for each todo item
     * @exception ServiceException on service error
     */
    public  void delete(int id)throws ServiceException;
    
    /**
    * This method is used to edit the todo item
    * @param get gets the autogenerated value which is unique for each todo item
    * @param set gets the new todo value entered by the user
    * @exception ServiceException on service error
    */
    public void update(int get,String set)throws ServiceException;
    
    /**
    * This method is to list the Todo items of a particular user
    * @param s gets the name of the user
    * @return it returns todo list
    */
    public List<App> listing1(String s);
}